---
project id: 2
test report: True
table mapping: {11362: 8, }
test report run id: 1494
template path: D:/user_data/Martin/OneDrive - Straumann Group/Template/QUF73-2485 Template Test Report (v1.0) (ID 3999).docx
output doc name: D:/user_data/Martin/OneDrive - Straumann Group/Temp/test.docx
