---
project id: 2
objective: The objective is to validate the software
scope: DW-IO-100
Requirement: "002, 007, 031"


# use CSV template:
# True: use the CSV Template pointed by "template path" 3 sections
#    Installation Qualification, Operational Qualifiaction, Performance Qualification
#    Use the variable "testrail parent section id" which is top level that include the 3 sections IQ, OQ, PQ.
# False: use user defined template pointed by "template path"
#    define in "table mapping" a dict of the section to import and corresponding word table ID
#    {test rail section_id: table id in word doc, ...}  ex: {74567: 2, 74568: 3}
#    the word doc should already tables created with one blank row.
use CSV template: False
#table mapping: {11476: 3}    # Ex: {11362: 2, 6369: 3, 9521: 4}
<<<<<<< HEAD
table mapping: {11956: 3}
testrail parent section id: 11956   # Use only for option Use CSV = True
=======
table mapping: {7742: 8}
testrail parent section id: 7742   # Use only for option Use CSV = True
>>>>>>> 34ab59f283082574c7d6e50ae7f321eaa8ca8ec4

test report: True          #True for test report False for test specification
test report run id: 1538    # Enter the run id from test rail (Rxxxx)

# output doc name is path and file name where the document is created
<<<<<<< HEAD
output doc name: C:\Users\mcarufel\OneDrive - STG-Business\project\Projector flex PCB\filled doc2.docx
# template path: D:\user_data\Martin\OneDrive\Documents\git\PycharmProjects\wordDoc\QUF63-5448 Template CSV Validation Specifications (v1.2).docx
# template path: QUF73-2485 Template Test Report (v1.0).docx

template path: C:\Users\mcarufel\OneDrive - STG-Business\Template\QUF73-2484 Template Test Specification (v1.3).docx
=======
output doc name: D:\user_data\Martin\OneDrive - Straumann Group\DHF\100 Verification & Validation\101 Verification\Hardware\IO HP3\CR-230117-IO-1 Handpiece BOM change C07 and C08\filled doc2.docx
# template path: D:\user_data\Martin\OneDrive\Documents\git\PycharmProjects\wordDoc\QUF63-5448 Template CSV Validation Specifications (v1.2).docx
# template path: QUF73-2485 Template Test Report (v1.0).docx

template path: D:\user_data\Martin\OneDrive - Straumann Group\Template\QUF73-2485 Template Test Report (v1.0) (ID 3999).docx
>>>>>>> 34ab59f283082574c7d6e50ae7f321eaa8ca8ec4
#template path: D:\temp\DEX73-5800 HPC Test Station EM P508 Validation Report (v1.2) - template.docx
...