---
project id: 2
test report: False
table mapping: {13575: 3, }
test report run id: 0
template path: D:/user_data/Martin/OneDrive - Straumann Group/Template/QUF73-2484 Template Test Specification (v1.3).docx
output doc name: D:/user_data/Martin/OneDrive - Straumann Group/Temp/Window glue cure reduced time.docx
